### ISSUE TITLE
Pas filles missing

### ISSUE THREAD

**Issue by limelect** [BitmasterXor/Chrome-Password-Recovery#1]
Too many pas files missing in uses
I am using only free components
So yours is unusable in ALL YOUR PROJECTS

**Comment by BitmasterXor** [comment]
> Too many pas files missing in uses I am using only free components So yours is unusable in ALL YOUR PROJECTS

You where right man, I took out all un-needed pas files and have reverted the code to only use native solutions and windows API calls... The ONLY components which are now required are the TMS crypto components which i have also packed with this repository all you have to do is  install them from source and your good to go you can find them in the folder named: Cryptography Library (REQUIREMENT YOU MUST INSTALL IT FROM SOURCE)

Also Note I have this same exact project working with a more native open source crypto suite known as Mormot V2 in case your interested I have also cleaned up its code just like i did this one and removed any and all premium components / libraries from its source so it should compile right out of the box (Given you have Mormot properly setup with your IDE)  

if your interested here are the links:
Mormot V2 Github page: https://github.com/synopse/mORMot2
And the link to my Chrome password recovery using mormot V2: https://github.com/BitmasterXor/Chrome-Mormot-V2-Edition


I Hope this helps you out, you should EASILY be able to get these working at this point. 
If you require assistance let me know ill be happy to help you get setup.

**Comment by BitmasterXor** [comment]
Closing Issue as 100% resolved I have personally tested this code on Delphi (10, 11 and the new 12 Athens IDE) "Freshly Installed IDE's" nothing added just barebone IDE installation. 
Working 100% NO DEPENDANCIES other than TMS crypto pack and if instructions are followed properly to get those installed the project opens and compiles without any issues at all on all 3 IDE's i have tested with.
